double? screenWidth;
double? screenHeight;
String appLogo = 'assets/images/logo.png';
String illuStration1 = 'assets/images/illustration1.png';
String illusStration2 = 'assets/images/Illustration2.png';
String illusStration3 = 'assets/images/illustration3.png';
String dashBoard = 'assets/images/dashboard.png';
String cocaCola = 'assets/images/cocacola.png';
String facebook = 'assets/images/fb.png';
String google = 'assets/images/google.png';
String linkedIn = 'assets/images/linkedin.png';
String samsung = 'assets/images/samsung.png';
String vector1 = 'assets/images/vector.png';
String vector2 = 'assets/images/vector1.png';
String illustrator = 'assets/images/Illustrator.png';
